---
url: https://github.com/khenderick/esphome-legacy-addons
arch:
- amd64
- armv7
- aarch64
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: true
ports:
  6052/tcp: null
map:
- ssl:ro
- config:rw
discovery:
- esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  relative_url: str?
  leave_front_door_open: bool?
backup_exclude:
- '*/*/'
init: false
name: ESPHome 2023.6
version: 2023.6.5
slug: esphome-legacy-2023-6
description: ESPHome legacy add-on (version 2023.6.5)
image: ghcr.io/esphome/esphome-hassio
